### ISSUE TITLE
Checkbox label not read when navigating to input using arrow keys

### ISSUE THREAD

**Issue by mteffaha** [nvaccess/nvda#5483]
Hello.
Using the setting replicated in the following jsfiddle : 
[jsfiddle link](https://jsfiddle.net/mteffaha/fb7e5vzd/7/)

nvda does not read neither the label nor the aria-labelledby div for the checkbox.
this issue is only existing whith the specific css available in the jsfiddle : 

```css
input[type="checkbox"]{
    float:left;    
}

label{
    display: block;    
}

```
thanks in advance.
Best regards
